apiVersion: v1
kind: ConfigMap
metadata:
  name: mediawiki-conf-1
data:
  CustomSettings.php: |
    <?php
    $wgServer = '//' . $_SERVER['HTTP_HOST'];
    $wgArticlePath = '/wiki/$1';
    $wgScriptPath = '/w';
    # Enable database caching
    $wgMainCacheType = CACHE_DB;
    /**
     * VisualEditor, Citoid and co
     */
    wfLoadExtension( 'VisualEditor' );
    wfLoadExtension( 'ParserFunctions' );
    wfLoadExtension( 'TemplateData' );
    wfLoadExtension( 'Cite' );
    wfLoadExtension( 'Citoid' );
    $wgDefaultUserOptions['visualeditor-enable'] = 1;
    $wgHiddenPrefs[] = 'visualeditor-enable';
    $wgVirtualRestConfig['modules']['restbase'] = array(
      'url' => 'http://restbase-svc:7231',
      'domain' => 'localhost',
      'forwardCookies' => true,
      'parsoidCompat' => false
    );
    /**
     * ChangeProp and EventBus
     */
    wfLoadExtension( 'EventBus' );
    $wgEventServiceUrl = "http://eventlogging-service-svc:8085/v1/events";
    /**
     * Math
     */
    wfLoadExtension( 'Math' );
    $wgMathValidModes[] = 'mathml';
    $wgDefaultUserOptions['math'] = 'mathml';
    $wgMathFullRestbaseURL = '/api/rest_';
    #unset($GLOBALS['wgMathMathMLUrl']);
    /**
     * Mobile Content Service
     */
    wfLoadExtension( 'MobileFrontend' );
    wfLoadExtension( 'TextExtracts' );
    wfLoadExtension( 'PageImages' );
