apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mediawiki-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service_name: mediawiki
    spec:
      containers:
        - name: mediawiki
          #image: devyanial07/mediawiki
          image: wikimedia/mediawiki:1.30.0-wmf4
          ports:
            - containerPort: 80
          env:
            - name: MEDIAWIKI_SITE_SERVER
              value: 'configured-in-CustomSettings.php'
            - name: MEDIAWIKI_SITE_NAME
              value: MediaWiki
            - name: MEDIAWIKI_SITE_LANG
              value: en
            - name: MEDIAWIKI_ADMIN_USER
              value: admin
            - name: MEDIAWIKI_ADMIN_PASS
              value: admin
            - name: MEDIAWIKI_UPDATE
              value: 'true'
            - name: MEDIAWIKI_DB_TYPE
              value: mysql
            - name: MEDIAWIKI_DB_USER
              value: root
            - name: MEDIAWIKI_DB_PASSWORD
              value: password
            - name: MEDIAWIKI_DB_HOST
              value: mysql-svc
            - name: MEDIAWIKI_RESTBASE_URL
              value: http://restbase-svc:7231/localhost/v1
          volumeMounts:
            - name: mediawiki-storage
              mountPath: /data
            - name: mediawiki-conf
              mountPath: /conf

      volumes:
        - name: mediawiki-storage
          hostPath:
            path: /var/lib/mediawiki-containers/mediawiki
        - name: mediawiki-conf
          configMap:
            name: mediawiki-conf-1

---
apiVersion: v1
kind: Service
metadata:
  name: mediawiki-svc
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    service_name: mediawiki
